### ISSUE TITLE
Write value example

### ISSUE THREAD

**Issue by setter** [danielwippermann/resol-vbus-java#1]
Hi Daniel,

Great to see a java fork of your nodejs project :-)

Is it possible to add a write value example (With protocol V2) ? 

Thanks in advance

**Comment by danielwippermann** [comment]
Hi Sebastien,

I'll put together an example in the next couple of days. Any preferred controller to start with? :)

**Comment by danielwippermann** [comment]
Hi Sebastien,

I added the customization example with this commit: https://github.com/danielwippermann/resol-vbus-java/commit/aec28d45d513c7d1400e46d0b62344c67c167847

In theory it should work with a CS Plus, but I have not been able to test it because the controller I borrowed was incomplete :) . I'm currently planning to do the testing tomorrow and hopefully fix bugs found in the course of this as well.

I'll let you know how the testing worked out :)

**Comment by danielwippermann** [comment]
Hi Sebastien,

the first shot at the customizer example was quite okay. I needed to fix a bug and added a bit of debug output as well as setting the clock to the correct time (+/- 1 minute) in the example app. Please give it a shot and feel free to open another issue if things don't work for you.

I'll close this issue once the wiki page describing the example app is created and filled :)

**Comment by danielwippermann** [comment]
Here is a link to the wiki page:

https://github.com/danielwippermann/resol-vbus-java/wiki/Load-and-save-controller-configuration

Feel free to open another issue if you encounter any problems.
