### ISSUE TITLE
Loading the VSF from resource fails sometimes

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#10]
In my environment I had the situation that reading the VSF resoure fails in SpecificationFile.fromStream(InputStream is):
is.read(buffer) returns before the FULL file is loaded (due to whatever reason)

I changed it locally to use the Guava library to do
byte[] bytes = ByteStreams.toByteArray(is);

with that it works. For the general case here it seems best to put a loop around the is.read until it returns -1. With that it is also possible to dynamically resize the byte array to handle all future VSF file increases without out of bounds accesses...

**Comment by danielwippermann** [comment]
Oh, did not know that a commit message auto-closes the corresponding issue...

Just out of curiosity: which OS are you using? Because my macOS did not show the behaviour you described... Seems not to be "write-once-run-anywhere" after all :)

The commit itself only implements the loop around the `read` call, not the auto-growing buffer. The 1MB limitation is a currently undocumented limitation of the VSF file format version 1 and will be dealt with when version 2 comes out eventually.

**Comment by ramack** [comment]
I run it on Debian Linux with Sun Jdk without issues. After running the openhab binding from the jar on a RaspberryPI3 on some other (don't remember what it was by heart) JDK. - there the read returned before reading until EOF.

**Comment by danielwippermann** [comment]
Thanks for the info, I hope the commit fixes that issue. If not feel free to reopen it or create a new one.

**Comment by ramack** [comment]
Looks good!
