### ISSUE TITLE
data point localization

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#3]
I did not yet use this code, but have a question. How shall the data points be interpreted and their names localized? It looks like the SpecificatinData is generated from the XML data used in the RSC. Is there a script to do that and how should we use it in a generic implementation supporting 'all' devices and languages?

**Comment by danielwippermann** [comment]
Hi Raphael,

you are right, the [file `SpecificationData.java`](https://github.com/danielwippermann/resol-vbus-java/blob/master/vbus/src/main/java/de/resol/vbus/SpecificationData.java) was auto-generated from the XML files distributed in the RSC installer. The tool used was basically the [`specification-importer`](https://github.com/danielwippermann/resol-vbus/tree/master/tools/specification-importer) from the JavaScript project with a specialized Java output generator (which was not commited to the repo).

The XML format used back then only supported limited localization, but the XML content (and its auto-generated Java source) served its purpose. For a long time it only supported German (that restriction was removed later but most of the files don't carry localization info).

Nowadays I'd rather switch to the VSF (VBus Specification File) mechanism like the [JavaScript](https://github.com/danielwippermann/resol-vbus/blob/master/src/specification-file.js) and the [Rust](https://github.com/danielwippermann/resol-vbus.rs/blob/master/src/specification_file.rs) libraries already use. That format at least supports English and French out-of-the-box in addition to German and is much more compact than the auto-generated sources.

Adding VSF parsing support should not be too complicated. But if you are looking for short-term solution I'll clean up the Java generator plugin for the `specification-importer` tool and upload to the other repo so that you can maintain / edit your own XML files and re-generate the Java source based on them.

**Comment by ramack** [comment]
@danielwippermann you are so fast. I would say, 1ad96874c192e9ee0494cef360dca19fcca95fbc closes this. Thanks!
