### ISSUE TITLE
Integration of resol-vbus-java

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#6]
What is the was to integrate resol-vbus-java into other projects, like an OpenHAB binding for example. Copying the code is not so clean. Is there a way to use maven to integrate a tagged version of this library here? Or should we think of a jar distributable?

**Comment by danielwippermann** [comment]
To be honest: I have no clue and always deferred that decision until somebody actually wanted to use the lib :)
If I had to decide a way on my own I thing I would have followed [this StackOverflow answer on how to deploy artifacts to GitHub](https://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github#14013645). But since I don't write Java for a living anymore I don't know the state-of-the-art way to solve this, so I'm open for alternative suggestions!

**Comment by danielwippermann** [comment]
Sounds good to me.

I created a branch "releases", bumped all version identifiers and tagged the current state of the repo as "v0.2.0", built a JAR file from it and put it on the "releases" branch tagged as "rel-v0.2.0". 

That way it should be easy to identify which source code belongs to which release.

**Comment by danielwippermann** [comment]
I close this for now, feel free to reopen it or create a new issue if you think this is not solved yet.

**Comment by ramack** [comment]
In the [Changelog](https://github.com/danielwippermann/resol-vbus-java) the release 0.3 is documented, but neither a tag nor a release jar is available. Could you do me the favor and build the jar for 0.3?

**Comment by danielwippermann** [comment]
You can find the JAR under the (freshly created) GitHub release for 0.3.0: https://github.com/danielwippermann/resol-vbus-java/releases/tag/v0.3.0

**Comment by ramack** [comment]
thanks a lot!
